<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="TourCrud.aspx.cs" Inherits="LimpopoWorld.TourCrud" %>

<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>Tour CRUD Operations</title>
    <style type="text/css">
        body {
            font-family: "system-ui";
            background: linear-gradient(to right bottom, #8E0E00, #1F1C18);
            color: white;
            margin: 0;
            padding: 0;
        }
        .container {
            padding: 20px;
        }
        .grid-view {
            width: 90%;
            margin: 20px auto;
            background-color: #333;
            border-collapse: collapse;
            text-align: center;
        }
        .grid-view th, .grid-view td {
            padding: 15px;
        }
        .grid-view th {
            background-color: #444;
            color: white;
        }
        .grid-view td {
            background-color: #555;
        }
        .grid-view tr:nth-child(even) {
            background-color: #666;
        }
        .grid-view tr:hover {
            background-color: #777;
        }
        .grid-view img {
            width: 100px;
            height: 100px;
            object-fit: cover;
        }
        .action-buttons {
            display: flex;
            justify-content: center;
            gap: 10px;
        }
        .action-buttons a, .action-buttons input {
            background-color: #04AA6D;
            color: white;
            padding: 10px 20px;
            text-decoration: none;
            border: none;
            border-radius: 5px;
            cursor: pointer;
            transition: background-color 0.3s ease;
        }
        .action-buttons a:hover, .action-buttons input:hover {
            background-color: #028a5e;
        }
    </style>
</head>
<body>
    <form id="form1" runat="server">
        <div class="container">
            <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True"
                DataKeyNames="TOUR_ID" DataSourceID="SqlDataSource1" CssClass="grid-view">
                <Columns>
                    <asp:BoundField DataField="TOUR_ID" HeaderText="Tour ID" InsertVisible="False" ReadOnly="True" SortExpression="TOUR_ID" />
                    <asp:BoundField DataField="TOUR_NAME" HeaderText="Tour Name" SortExpression="TOUR_NAME" />
                    <asp:BoundField DataField="PLACE" HeaderText="Place" SortExpression="PLACE" />
                    <asp:BoundField DataField="DAYS" HeaderText="Days" SortExpression="DAYS" />
                    <asp:BoundField DataField="PRICE" HeaderText="Price" SortExpression="PRICE" />
                    <asp:BoundField DataField="LOCATIONS" HeaderText="Locations" SortExpression="LOCATIONS" />
                    <asp:BoundField DataField="TOUR_INFO" HeaderText="Tour Info" SortExpression="TOUR_INFO" />
                    <asp:TemplateField HeaderText="Picture">
                        <ItemTemplate>
                            <img src='<%# "Tour_pics/" + Eval("pic") %>' alt="Tour Picture" />
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField>
                        <EditItemTemplate>
                            <div class="action-buttons">
                                <asp:LinkButton ID="UpdateButton" runat="server" CommandName="Update" Text="Update" />
                                <asp:LinkButton ID="CancelButton" runat="server" CommandName="Cancel" Text="Cancel" />
                            </div>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <div class="action-buttons">
                                <asp:LinkButton ID="EditButton" runat="server" CommandName="Edit" Text="Edit" />
                                <asp:LinkButton ID="DeleteButton" runat="server" CommandName="Delete" Text="Delete" />
                            </div>
                        </ItemTemplate>
                    </asp:TemplateField>
                </Columns>
                <FooterStyle BackColor="#CCCC99" />
                <HeaderStyle BackColor="#6B696B" Font-Bold="True" ForeColor="White" />
                <PagerStyle BackColor="#F7F7DE" ForeColor="Black" HorizontalAlign="Right" />
                <RowStyle BackColor="#F7F7DE" HorizontalAlign="Center" />
                <SelectedRowStyle BackColor="#CE5D5A" Font-Bold="True" ForeColor="White" />
                <SortedAscendingCellStyle BackColor="#FBFBF2" />
                <SortedAscendingHeaderStyle BackColor="#848384" />
                <SortedDescendingCellStyle BackColor="#EAEAD3" />
                <SortedDescendingHeaderStyle BackColor="#575357" />
            </asp:GridView>
            <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:dbconnection %>" 
                DeleteCommand="DELETE FROM [Tour] WHERE [TOUR_ID]=@TOUR_ID" 
                SelectCommand="SELECT * FROM [Tour]" 
                UpdateCommand="UPDATE [Tour] SET [TOUR_NAME]=@TOUR_NAME, [PLACE]=@PLACE, [DAYS]=@DAYS, [PRICE]=@PRICE, [LOCATIONS]=@LOCATIONS, [TOUR_INFO]=@TOUR_INFO WHERE [TOUR_ID]=@TOUR_ID">
            </asp:SqlDataSource>
        </div>
    </form>
</body>
</html>
